### ISSUE TITLE
Matlab R2023a Error: Class 'FRDmod' is not allowed to define a 'subsref' method.

### ISSUE THREAD

**Issue by rhimas-arcsec** [meco-group/lc_toolbox#1]
Since I updated Matlab from R2021a to R2023a, I run into the following error when I'm trying to identify a system system with the function `nonpar_ident()` at this line: 
https://github.com/meco-group/lc_toolbox/blob/bf08f51fe64416fc736acc5a22730836fa5fc22d/Modules/Identification/nonpar_ident.m#L118
`Error using FRDmod`
`Class 'FRDmod' is not allowed to define a 'subsref' method.`

In the R2021a version everything still works fine. 
Is there a fix to solve this issue in the R2023a version?

**Comment by ljbs** [comment]
Hi Rhimas. For some mysterious reason, I didn't receive a notification of your issue and I had to learn about it by accident. We're indeed aware of this. Mathworks changed something in a model class (`frd`) we are inheriting from in `FRDmod`, which causes a kind of a conflict: we are not allowed to overload `subsref` anymore in `FRDmod`, but at the same time we _have to_ because it is an abstract method in `Model`, which `FRDmod` also inherits from. 

There is no obvious workaround (maybe a dirty hack could be to make `Model` no longer an abstract class and remove the `subsref` implementation both in that class as well as in `FRDmod`, but I'm not entirely sure that won't cause other problems). It's on our to-do list, in any case, given that we should fix the problem soon anyway for students using recent MATLAB versions, who are the main users ;-).

**Comment by ljbs** [comment]
@rhimas-arcsec Whenever convenient, could you maybe try the branch [`issue_1`](https://github.com/meco-group/lc_toolbox/tree/issue_1) and check whether all of your existing code still runs (in R2023a)? The issue should be resolved, but it would be great if you could also test whether nothing else is broken now ;-). For me, everything still seems to work fine.

**Comment by rhimas-arcsec** [comment]
@ljbs I tried the `issue_1` branch with my existing code and encountered one minor issue. One line in my code was extracting bode data as follows: 
```
% Bode options
opts = bodeoptions('cstprefs');
opts.Grid = 'on';
opts.PhaseWrapping = 'on';
opts.PhaseWrappingBranch = -270;

% Bode
[mag,phase,wout] = bode(G_nonpar, opts);
```
with `G_nonpar` a 1x1 FRDmod. 
This returns the following error: 
```
Error using DynamicSystem/bode
This syntax does not take plot options.

Error in Model/bode (line 174)
            [varargout{1:nargout}] = bode(varargin{:});

Error in FRDmod/bode (line 115)
            [varargout{1:nargout}] = bode@Model(varargin{:});
```
I tried converting the `FRDmod` to a `frd` with `std()`, but even then it still didn't work. It also doesn't work with `LTIDSSmod`. Without the optional command `opts`, it works fine. I guess the `opts` are just not supported by the toolbox anymore. However, I thought it would work when converting it with `std()`.

Is there a quick fix for this issue?

Everything else seems to work! :)

**Comment by ljbs** [comment]
@rhimas-arcsec I think that's just a syntax change in MATLAB. You're using `bode` with output arguments here and that doesn't seem to work for regular models like `frd`, `ss`, etc. (and therefore also not for their toolbox counterparts) in the new MATLAB releases. I think it has also never been officially supported, by the way: the documentation page of [`bode`](https://nl.mathworks.com/help/ident/ref/dynamicsystem.bode.html) doesn't mention `bodeoptions`, and the [`bodeoptions`](https://nl.mathworks.com/help/ident/ref/bodeoptions.html) page doesn't mention a `bode` syntax with output arguments. So you have probably been exploiting a bug in their code up to now ;-).

**Comment by rhimas-arcsec** [comment]
@ljbs If I look at the references, indeed my code might be a bit shady 😄
Ok, I think this issue is fixed then. Thank you very much!
